name: Trigger auto deployment for container-app-ipbjz7mvesgfk

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/container-app-ipbjz7mvesgfk-AutoDeployTrigger-d8c40ad8-56ac-42d3-b6c3-3df61507c582.yml'

  # Allow mannually trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.CONTAINERAPPIPBJZ7MVESGFK_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.CONTAINERAPPIPBJZ7MVESGFK_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.CONTAINERAPPIPBJZ7MVESGFK_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v1
        with:
          appSourcePath: ${{ github.workspace }} 
          registryUrl: containerregistryipbjz7mvesgfk.azurecr.io
          registryUsername: ${{ secrets.CONTAINERAPPIPBJZ7MVESGFK_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.CONTAINERAPPIPBJZ7MVESGFK_REGISTRY_PASSWORD }}
          containerAppName: container-app-ipbjz7mvesgfk
          resourceGroup: charris-indymeet8
          imageToBuild: containerregistryipbjz7mvesgfk.azurecr.io/container-app-ipbjz7mvesgfk:${{ github.sha }}
          dockerfilePath: Dockerfile


